---
# this options overwrite the defaults

# additional

pi:
  hostname: your_hostname

main:
    iface: wlan0mon
    whitelist:
        - 'YOUR WIFI HERE'

ai:
    enabled: true

ui:
    display:
        enabled: true
        video:
            enabled: true
            address: '10.0.0.2'
            port: 8080

bettercap:
    handshakes: /root/handshakes
